---
server:
    port: 9090
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: 
        username: sa
        url : jdbc:h2:file:C:/Users/Felipe Galaz/test
        #url : jdbc:h2:file:/home/fgalaz/globalTest
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console 