---
server:
    port: 9090
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: 
        url: jdbc:h2:mem:test
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console 